/**
 * Rankings data store.
 *
 * Priority:
 *  1. backend API  (/api/rankings?major=X)  — when Spring Boot is running
 *  2. local JSON   (src/data/rankings.json)  — after running/importing rankings
 *  3. empty map                              — no data yet
 *
 * The local JSON is generated by:
 *   cd scraper && python scrape_rankings.py --major national-universities --limit 100 --sync
 */

import axios from 'axios'

const MAJOR_KEY = 'ct_selected_major'

// ── In-memory cache: majorSlug → Map<normalizedName, rank> ────────────────────
const cache = new Map()

async function loadMajor(majorSlug) {
  if (cache.has(majorSlug)) return cache.get(majorSlug)

  let entries = []

  // 1. Try backend
  try {
    const { data } = await axios.get(`/api/rankings?major=${majorSlug}`, { timeout: 3000 })
    entries = data
  } catch {
    // 2. Try local JSON file
    try {
      const mod = await import('../data/rankings.json')
      const all = mod.default ?? []
      const major = all.find((m) => m.slug === majorSlug)
      entries = major?.rankings ?? []
    } catch {
      // No data available
    }
  }

  // Build name → rank map (normalise names for fuzzy matching)
  const map = new Map()
  for (const entry of entries) {
    const name = entry.collegeName ?? entry.name ?? ''
    if (name && entry.rank) {
      map.set(normaliseName(name), entry.rank)
    }
  }

  cache.set(majorSlug, map)
  return map
}

/** Normalise a college name for comparison (lowercase, drop punctuation/common suffixes). */
function normaliseName(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')          // strip punctuation
    .replace(/\b(university|college|institute|of|the|at|main campus)\b/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/** Look up the rank of a college in a given major. Returns null if not ranked. */
export async function getRank(majorSlug, collegeName) {
  if (!majorSlug || !collegeName) return null
  const map = await loadMajor(majorSlug)
  if (!map.size) return null

  const key = normaliseName(collegeName)

  // Exact match
  if (map.has(key)) return map.get(key)

  // Partial match — find longest overlap
  let best = null
  let bestScore = 0
  for (const [stored, rank] of map) {
    if (key.includes(stored) || stored.includes(key)) {
      const score = Math.min(stored.length, key.length)
      if (score > bestScore) { best = rank; bestScore = score }
    }
  }
  return best
}

/** Preload a major's rankings into the cache. */
export function preloadMajor(majorSlug) {
  if (majorSlug) loadMajor(majorSlug)
}

// ── User major preference (persisted to localStorage) ─────────────────────────

export function getSavedMajor() {
  return localStorage.getItem(MAJOR_KEY) ?? ''
}

export function saveMajor(slug) {
  if (slug) localStorage.setItem(MAJOR_KEY, slug)
  else localStorage.removeItem(MAJOR_KEY)
}

// ── Available majors list (for the dropdown) ──────────────────────────────────

const ALL_MAJORS = [
  { slug: 'computer-science',       name: 'Computer Science' },
  { slug: 'electrical-engineering', name: 'Electrical Engineering' },
  { slug: 'mechanical-engineering', name: 'Mechanical Engineering' },
  { slug: 'chemical-engineering',   name: 'Chemical Engineering' },
  { slug: 'computer-engineering',   name: 'Computer Engineering' },
  { slug: 'aerospace-engineering',  name: 'Aerospace Engineering' },
  { slug: 'biomedical-engineering', name: 'Biomedical Engineering' },
  { slug: 'civil-engineering',      name: 'Civil Engineering' },
  { slug: 'business',               name: 'Business' },
  { slug: 'accounting',             name: 'Accounting' },
  { slug: 'finance',                name: 'Finance' },
  { slug: 'national-universities',  name: 'National Universities (Overall)' },
  { slug: 'liberal-arts',           name: 'Liberal Arts' },
  { slug: 'nursing',                name: 'Nursing' },
  { slug: 'psychology',             name: 'Psychology' },
  { slug: 'biology',                name: 'Biology' },
]

export async function getAvailableMajors() {
  // Try backend first, fall back to static list
  try {
    const { data } = await axios.get('/api/rankings/majors', { timeout: 3000 })
    if (data?.length) return data
  } catch {}

  // Check which majors have data in the local JSON
  try {
    const mod = await import('../data/rankings.json')
    const scraped = new Set((mod.default ?? []).map((m) => m.slug))
    if (scraped.size) return ALL_MAJORS.filter((m) => scraped.has(m.slug))
  } catch {}

  // Return the full static list (items will show "—" until scraper is run)
  return ALL_MAJORS
}

